#!/usr/bin/env python3
"""Regenerate the bundled vendor database from the IEEE OUI registry.

  >>> THIS IS A DEVELOPER SCRIPT. IT IS NOT PART OF THE SHIPPED PACKAGE. <<<

It is the only file in this repository that makes a network request, and it is
run by hand, by a maintainer, to refresh `data/oui.csv` before a release. The
engine itself never contacts anything -- that is the whole reason the database
is bundled rather than queried at runtime.

Do not import this module from library code.

    python scripts/update_oui.py                # full registry (~35k prefixes)
    python scripts/update_oui.py --merge        # add to the curated list
    python scripts/update_oui.py --dry-run      # report only, write nothing

The full registry is roughly 1.3 MB as CSV, which is acceptable to ship and
removes the "unknown manufacturer" caveat from the README. The curated default
exists so the repository stays reviewable by hand.
"""

from __future__ import annotations

import argparse
import csv
import io
import re
import sys
import urllib.request
from pathlib import Path
from typing import Dict

IEEE_CSV_URL = "https://standards-oui.ieee.org/oui/oui.csv"
OUTPUT_PATH = Path(__file__).resolve().parent.parent / "src" / "edgedefense_core" / "data" / "oui.csv"

HEADER = """\
prefix,vendor
# Generated by scripts/update_oui.py from the IEEE OUI registry.
# Bundled deliberately: this tool never performs a remote vendor lookup.
"""

#: Corporate suffixes that add length without adding meaning in a device list.
_NOISE = re.compile(
    r"\s*(,?\s*(inc|inc\.|incorporated|corp|corp\.|corporation|co|co\.|company|"
    r"ltd|ltd\.|limited|llc|l\.l\.c\.|gmbh|s\.a\.|sa|ag|kg|bv|b\.v\.|nv|plc|"
    r"technologies|technology|electronics|international)\b\.?)+$",
    re.IGNORECASE,
)


def tidy_vendor(name: str) -> str:
    """Shorten a registry name to something a person would recognise."""
    cleaned = " ".join(name.split())
    cleaned = _NOISE.sub("", cleaned).strip(" ,.")
    return cleaned or name.strip()


def fetch_registry(url: str = IEEE_CSV_URL) -> str:
    """Download the IEEE registry. Raises on any failure -- fail loudly here."""
    request = urllib.request.Request(url, headers={"User-Agent": "edgedefense-oui-updater"})
    with urllib.request.urlopen(request, timeout=120) as response:
        return response.read().decode("utf-8", errors="replace")


def parse_registry(content: str) -> Dict[str, str]:
    """Extract {prefix: vendor} from the registry CSV."""
    table: Dict[str, str] = {}
    reader = csv.DictReader(io.StringIO(content))

    for row in reader:
        prefix = (row.get("Assignment") or "").strip().upper()
        vendor = (row.get("Organization Name") or "").strip()
        if not re.fullmatch(r"[0-9A-F]{6}", prefix) or not vendor:
            continue
        if vendor.lower() in ("private", "ieee registration authority"):
            continue
        table[prefix] = tidy_vendor(vendor)

    return table


def load_existing(path: Path) -> Dict[str, str]:
    """Read the currently bundled database, so --merge can preserve curation."""
    table: Dict[str, str] = {}
    if not path.exists():
        return table

    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("prefix,"):
            continue
        prefix, _, vendor = line.partition(",")
        if re.fullmatch(r"[0-9A-F]{6}", prefix.strip().upper()) and vendor.strip():
            table[prefix.strip().upper()] = vendor.strip()
    return table


def write_database(table: Dict[str, str], path: Path) -> None:
    """Write the database sorted by prefix, so diffs stay reviewable."""
    lines = [HEADER]
    lines.extend(f"{prefix},{table[prefix]}" for prefix in sorted(table))
    path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--url", default=IEEE_CSV_URL, help="registry URL")
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH, help="destination CSV")
    parser.add_argument(
        "--merge",
        action="store_true",
        help="keep existing curated entries, adding registry entries alongside them",
    )
    parser.add_argument("--dry-run", action="store_true", help="report only, write nothing")
    args = parser.parse_args()

    existing = load_existing(args.output)
    print(f"Currently bundled: {len(existing)} prefixes")

    print(f"Fetching {args.url} ...")
    try:
        content = fetch_registry(args.url)
    except Exception as exc:
        print(f"Download failed: {type(exc).__name__}: {exc}", file=sys.stderr)
        return 1

    registry = parse_registry(content)
    if not registry:
        print("Registry parsed to zero entries; refusing to overwrite.", file=sys.stderr)
        return 1
    print(f"Parsed from registry: {len(registry)} prefixes")

    if args.merge:
        # Curated names are usually friendlier ("Google Nest" vs the legal
        # entity), so they win on conflict.
        merged = {**registry, **existing}
    else:
        merged = registry

    print(f"Result: {len(merged)} prefixes (+{len(merged) - len(existing)})")

    if args.dry_run:
        print("--dry-run: nothing written.")
        return 0

    write_database(merged, args.output)
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
